### ISSUE TITLE
#1064 - You have an error in your SQL syntax

### ISSUE THREAD

**Issue by arielko** [deliciousbrains/wp-migrate-db#48] opened 2015-03-04 01:09 UTC
Error
SQL query:
# WordPress MySQL database migration
# 
# Generated: Monday 2. March 2015 21:03 UTC
# Hostname: localhost
# Database: `wordpress`
# --------------------------------------------------------

/*!40101 SET NAMES */;

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 8

![screen shot 2015-03-03 at 5 02 43 pm](https://cloud.githubusercontent.com/assets/11304845/6476206/e308f842-c1c7-11e4-808a-df0f5b1a3235.png)

Can you please help me fix this error, the hosting company wont share a way to fix this. I can't upload my DB.

Am i doing something wrong?

thx

**Comment by MarventusWP** [comment] 2015-03-09 01:47
@webaware 
Arielko,
This is definitely not you. There seems to be a bug with the "Compress file with gzip" plugin setting, since it is outputting corrupt Db dumps.
I was experiencing the same issue as you were, until I migrated without gzip compression and the file was perfectly fine. After realizing what the problem was coming from, I found another thread in WP Forums (other than my own) about this very same issue: https://wordpress.org/support/topic/error-with-sql-import?replies=3

@Brad and the WP Migrate Db Team: I can gladly run tests or provide any sort of background info you might require in order to fix this issue. However, in the meantime, I strongly suggest you make sure the gzip setting is off by default upon first installation.

Thanks!

**Comment by bradt** [comment] 2015-03-11 17:38
This would occur if `DB_CHARSET` was set to an empty string in your wp-config.php. It should be set to the following in most cases:

```php
define('DB_CHARSET', 'utf8');
```

**Comment by jessems** [comment] 2016-06-12 11:44
My `DB_CHARSET` was set correctly, but I was still experiencing this issue.

Importing through the command line worked for me.

**Comment by UnionDesign** [comment] 2016-06-16 13:06
Getting the same error with define('DB_CHARSET', 'utf8'); set. Saying the error is on line 1 near "-"

**Comment by UnionDesign** [comment] 2016-06-16 13:15
Ok I noticed it would get so far before the error. So I displayed which tables were being migrated and the failure was always happening on the tables created by "All In One WP Security". When I exclude those tables the migration runs fine.

**Comment by MarcGuay** [comment] 2016-12-12 19:40
Had a similar problem where it was choking on every insert post line.  Seems as though phpMyAdmin was having a problem disgesting a compressed version of it.  Turned off the zipping in wp-migrate-db and uploading the raw SQL file and it worked fine.

**Comment by Jason-Murray** [comment] 2017-03-14 11:01
Ran in to this error earlier today, although a different manifestation of it as we were not using pma to restore any files etc, just using the pull functionality within Migrate DB Pro:

I could pull to local fine but another dev was getting SQL syntax error saying the error is on line 1 near "-" halfway through the options table.  I sent him my full local install and after he replaced it the pull ran correctly so this does seem to be linked to the filesystem in some way.

**Comment by mattgrshaw** [comment] 2017-03-14 15:23
@Jason-Murray Glad you got it working. If it happens again can you shoot us an email to nom@deliciousbrains.com?

Closing this issue in the meantime since it could be caused by many different things and isn't always related to WP Migrate DB.

**Closed by mattgrshaw** 2017-03-14 15:23 UTC
