### ISSUE TITLE
Zip file fails on creation

### ISSUE THREAD

**Issue by cwjsmith** [deliciousbrains/wp-migrate-db#151] opened 2024-11-20 16:14 UTC
Hi,

I have tried several time to run the migration but each time the migration ends ok but when I tried to download the zip file it fails, I cannot find wehre the zip file is to manually down load it so I assume it gets deleted automatically. My debug log shows the following.

[13-Nov-2024 11:07:27 UTC] WPMDB Error: Data cannot be unserialized. Scope: DeliciousBrains\WPMDB\Common\Replace::recursive_unserialize_replace().

this is repeated 28 times28 times
and
13-Nov-2024 11:07:36 UTC] WPMDB Find & Replace skipped: {"table":"wp_options","primary_key":"10973","column":"option_value","contains_match":false,"option_name":"GTranslate"}
[13-Nov-2024 11:07:36 UTC] WPMDB Find & Replace skipped: {"table":"wp_options","primary_key":"2462207","column":"option_value","contains_match":false,"option_name":"astra_partials_config_cache"}
[13-Nov-2024 11:14:32 UTC] PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/vhosts/mydomain.com/httpdocs//index.php/index.php) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Common/Filesystem/Filesystem.php on line 312
[13-Nov-2024 11:14:32 UTC] PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/vhosts/mydomain.com/httpdocs//license.txt/license.txt) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Common/Filesystem/Filesystem.php on line 312
[13-Nov-2024 11:14:32 UTC] PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/vhosts/mydomain.com/httpdocs//readme.html/readme.html) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Common/Filesystem/Filesystem.php on line 312
[13-Nov-2024 11:14:32 UTC] PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/vhosts/mydomain.com/httpdocs//wp-activate.php/wp-activate.php) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Common/Filesystem/Filesystem.php on line 312

Plus lots more of the same warnings

**Comment by cwjsmith** [comment] 2024-11-25 13:14
Is anyone there ?

**Comment by kevinwhoffman** [comment] 2024-11-27 23:06
Hi @cwjsmith,

We understand you’re encountering an issue during export. The expected behavior is for the ZIP file to be automatically downloaded to your machine and then removed from the server. Please note that `debug.log` messages about skipped data should not stop the export.

Based on the logs you provided, the erro appears to be related to:

> PHP Warning: is_dir(): open_basedir restriction in effect. File(/var/www/vhosts/mydomain.com/httpdocs//index.php/index.php) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) in /var/www/vhosts/mydomain.com/httpdocs/wp-content/plugins/wp-migrate-db/class/Common/Filesystem/Filesystem.php on line 312

This indicates that your server’s `open_basedir` setting restricts file access to certain paths. Please check if `open_basedir` is enabled and ensure no restrictions apply to your WordPress installation path.

If you don’t use `open_basedir`, then disabling it may allow the file to be exported. You may ask your host for assistance on this.

Please also ensure the `.zip` extension is installed and enabled on your server. Your host can help with this as well.

Please let us know how it goes!

**Comment by cwjsmith** [comment] 2024-11-28 08:32
Hi,
Thank you for replying, the setting on the server for open_basedir is {WEBSPACEROOT}{/}{:}{TMP}{/}  that is the same for my other website and as for as I know has not been changed, I have migrated this website several times without this error. I is when it is trying to write the zip file that it fails, I have looked for a copy on the server but I cannot find one. does it only create the zip file the once on my pc ?

**Comment by cwjsmith** [comment] 2024-12-05 11:49
Any Ideas please ?

**Comment by kevinwhoffman** [comment] 2024-12-05 13:41
Hi @cwjsmith, we'd like to confirm that the ZIP file is actually being created during the export process. If you are able to monitor `/wp-content/uploads/wp-migrate-db/` during the export process, you should see a ZIP file created as shown in the screenshot below:

![CleanShot 2024-12-05 at 08 33 31@2x](https://github.com/user-attachments/assets/146251eb-0841-4059-b0bd-bea568a924cd)

As the export proceeds, you may see a few `.part` files generated temporarily as the ZIP is built.

Please let us know what you are able to observe during the export process as this will tell us whether there is an issue creating the ZIP or if the issue is limited to downloading the ZIP.

**Comment by kevinwhoffman** [comment] 2024-12-05 21:00
Our engineers also mentioned that part of the path that appears in your error doesn't look right:

> File(/var/www/vhosts/mydomain.com/httpdocs//index.php/index.php) is not within the allowed path(s)...

The double slash `//` and two `index.php` strings in a row could be preventing the files from being exported.

Can you try exporting only the database and let me know if that works so we can narrow down the cause?

**Comment by cwjsmith** [comment] 2024-12-06 09:12
I tried again a couple of days ago and it still failed downloading the zip file to the browser, I have tried today as you suggested looking at the /wp-content/uploads/wp-migrate-db/  folder, nothing showed up in the folder but it worked ! I have no idea why, I have changed nothing.

**Comment by kevinwhoffman** [comment] 2024-12-06 13:12
@cwjsmith Interesting... could you give us more info about where the site is hosted? Is this a local site on your machine or is it hosted elsewhere? If it's hosted elsewhere, then an update to the hosting environment could have resolved the issue.

**Comment by cwjsmith** [comment] 2024-12-06 13:22
Hi,
It is hosted at webhosting.uk.com, yes it may have been an update by them, I hope so.
Thank you for your help

**Comment by kevinwhoffman** [comment] 2024-12-06 13:26
Thanks for the info. I'm going to close this out, but let us know if it happens again.

**Closed by kevinwhoffman** 2024-12-06 13:26 UTC
