### ISSUE TITLE
v2.3.0 -  #146 - scope: ajax_verify_connection_to_remote_site

### ISSUE THREAD

**Issue by mrkaluzny** [deliciousbrains/wp-migrate-db#136] opened 2022-04-05 10:00 UTC
After updating to 2.3.0 error  (#146 - scope: ajax_verify_connection_to_remote_site) is thrown

**Comment by philwp** [comment] 2022-04-05 14:48
@mrkaluzny @Striffly when you ran the update did you do it via the admin UI? 

We are trying to replicate the issue on our end. When the `ajax_verify_connection_to_remote_site` error is thrown did it seem like the connection process was taking longer than normal before the error message?

Thanks for the help.

**Comment by mrkaluzny** [comment] 2022-04-05 14:50
I've updated using wp-cli, the message is returned basically instantly after trying to connect, works fine after downgrade, I had WP Media Migrate plugin installed as well

**Comment by Striffly** [comment] 2022-04-12 12:04
Still have issue after upgrade to 2.3.2

Steps to reproduce :
- Upgrade manually on remote (replace plugin folder with FTP)
- Upgrade with composer on local
- Pull from remote with wp-cli : `500 Internal Server Error (scope: ajax_verify_connection_to_remote_site)`

**Comment by eugenf** [comment] 2022-04-13 00:01
I've experienced the same issue and was able to find this error when running the CLI command

![Screen Shot on 2022-04-13 at 12:00:07](https://user-images.githubusercontent.com/1702926/163073560-0914ae3e-66b2-4331-bc62-ca82d2fafc65.png)
d

**Comment by mrkaluzny** [comment] 2022-04-13 06:30
@eugenf nice find I noticed when the additional plugins were working the errors are caused. I’ll try with fresh install today

**Comment by AhmedTheGeek** [comment] 2022-04-13 22:56
@eugenf Thanks for posting the debugging output here. I can confirm that there's a bug in this piece of code and we're working on fixing it in the next release.

**Comment by Striffly** [comment] 2022-06-08 12:54
Hello

Has this issue been resolved with version 2.3.3 ? I don't see a reference in the changelog

**Comment by AhmedTheGeek** [comment] 2022-06-08 13:04
Hi @Striffly,

This issue wasn't fixed in version 2.3.3. However, we already worked a fix for it, and it's going to be a part of the upcoming 2.4.0 release.

**Comment by alexandre-tobia** [comment] 2022-07-25 08:35
@AhmedTheGeek  Hi, Any news ? Almost two month without any news .. :(

Thanks

**Comment by AhmedTheGeek** [comment] 2022-07-25 08:37
@alexandre-tobia We have a fix ready for this issue, and it's going to be included with the next major release 2.4.

**Comment by alexandre-tobia** [comment] 2022-07-25 08:41
Thanks for your reply. 
When the 2.4 will be out ?

**Comment by AhmedTheGeek** [comment] 2022-07-25 12:33
@alexandre-tobia I don't have an exact date. But it's not going to be a long wait 🙏.

**Comment by mrkaluzny** [comment] 2022-08-10 07:01
@AhmedTheGeek Any update? The issue is persisting on many installs, making this plugin completely useless. Any quick workarounds?

**Comment by alexandre-tobia** [comment] 2022-08-11 13:19
The only workaround i've found is to switch the theme (to use an official) on the remote before trying to pull/push.
But i agree, it's been too long since the issue has been reported, hard to understand for a paid product.

**Comment by philwp** [comment] 2022-08-12 12:08
@mrkaluzny 

`WP Migrate 2.3.4` was released today with a fix for this issue.

**Closed by philwp** 2022-08-12 12:08 UTC

**Comment by alexandre-tobia** [comment] 2022-08-13 10:58
Thanks !
