### ISSUE TITLE
Invalid header warning on install

### ISSUE THREAD

**Issue by mumbomedia** [deliciousbrains/wp-migrate-db#138] opened 2022-07-07 09:30 UTC
As mentioned on https://wordpress.org/support/topic/when-try-to-install-2-3-1-from-wp-plugin-repo-there-is-getting-error/ I also faced this issue.

**Comment by kevinwhoffman** [comment] 2022-07-12 00:18
Thanks for reporting. This error should be resolved by upgrading to WP Migrate Lite 2.3.2.

The error was caused by the renaming of the plugin from <strong>WP Migrate DB</strong> to <strong>WP Migrate Lite</strong>. This change caused WordPress to incorrectly identify the mu-plugin as the main plugin file due to a change in the alphabetical order of the plugin and mu-plugin names (talk about an edge case!). We've renamed the mu-plugin to <strong>WP Migrate Lite Compatibility</strong> to resolve the issue going forward. -KH

**Closed by kevinwhoffman** 2022-07-12 00:18 UTC
